print("=" * 80)
print("No main.py was found so one was created!")
print("Add your own code to this file: /home/developer/Projects/github/steven-aj/main.py")
print("=" * 80)
input("Key enter to close.")